(("inscheck" ("cscope" "-l" "-d")
  "~/work/inscheck/inscheck" "~/work/inscheck/inscheck")
 ("stubbers" ("cscope" "-l" "-d")
  "~/work/stubbers/stubbers" "~/work/stubbers/stubbers")
 ("mq" ("cscope" "-l" "-d") "~/work/mare/mq/mare" "~/work/mare/mq/mare")
 ("mare" ("cscope" "-l" "-d") "~/work/mare/base/mare" "~/work/mare/base/mare")
 ("misc" ("cscope" "-l" "-d") "~/work/mare/misc/mare" "~/work/mare/misc/mare")
 ("linux" ("cscope" "-l" "-d") "~/work/linux/linux-stable" "~/work/linux/linux-stable")
)
