
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(blink-cursor-mode nil)
 '(clang-format-executable "~/bin/clang-format")
 '(comint-eol-on-send t)
 '(comint-password-prompt-regexp
   "\\(\\(Verify password \\- \\|GSA \\|Enter \\|[Oo]ld \\|[Nn]ew \\|'s \\|login \\|Kerberos \\|CVS \\|UNIX \\| SMB \\|LDAP \\|\\[sudo] \\|^\\)[Pp]assword\\( (again)\\)?\\|pass phrase\\|\\(Enter \\|Repeat \\|Bad \\)?[Pp]assphrase\\)\\(?:, try again\\)?\\(?: for [^:]+\\)?:\\s *\\'")
 '(comint-use-prompt-regexp nil)
 '(compilation-ask-about-save nil)
 '(compilation-context-lines 3)
 '(compilation-error-screen-columns t)
 '(compilation-scroll-output t)
 '(compilation-skip-threshold 0)
 '(compilation-skip-visited nil)
 '(compile-command "make ")
 '(cscope-projects-file "~/.emacs.d/cscope-projects.el")
 '(cvs-auto-remove-handled t)
 '(cvs-find-file-and-jump nil)
 '(enable-recursive-minibuffers nil)
 '(explicit-bash-args (quote ("-i")))
 '(ffap-newfile-prompt t)
 '(focus-follows-mouse t)
 '(fringe-mode (quote (1 . 1)) nil (fringe))
 '(gdb-show-threads-by-default t)
 '(gdb-stack-buffer-addresses t)
 '(gdb-thread-buffer-addresses t)
 '(global-auto-revert-mode t)
 '(global-semantic-decoration-mode t)
 '(global-semantic-highlight-func-mode t)
 '(global-semantic-idle-breadcrumbs-mode t nil (semantic/idle))
 '(global-semantic-idle-completions-mode t nil (semantic/idle))
 '(global-semantic-idle-local-symbol-highlight-mode t nil (semantic/idle))
 '(global-semantic-idle-summary-mode t)
 '(global-semantic-stickyfunc-mode t)
 '(global-ycmd-mode t)
 '(grep-command "grep  -nH -e ")
 '(grep-find-command
   "find . \\( -name CVS -o -name SCCS -o -name .hg -o -name .git \\) -prune -o \\! \\( -name \\*~ -o -name .\\#\\* -o -name cscope.\\* \\) -type f -print0 | xargs -0 grep -n -e")
 '(grep-find-template
   "find <D> <X> -type f <F> -exec grep <C> -nH -e <R> \\{\\} +")
 '(grep-template "grep <X> <C> -nH  -e <R> <F>")
 '(grep-use-null-filename-separator nil)
 '(ido-default-file-method (quote selected-window))
 '(ido-everywhere t)
 '(indent-tabs-mode nil)
 '(indicate-buffer-boundaries nil)
 '(ispell-local-dictionary-alist nil)
 '(ivy-mode t)
 '(ivy-use-virtual-buffers t)
 '(large-file-warning-threshold 1000000)
 '(log-edit-confirm t)
 '(mac-option-modifier (quote (:ordinary meta :function alt :mouse alt)))
 '(markdown-command "multimarkdown")
 '(menu-bar-mode t)
 '(mouse-autoselect-window t)
 '(mouse-drag-copy-region t)
 '(mouse-wheel-progressive-speed nil)
 '(ns-command-modifier (quote meta))
 '(package-archives
   (quote
    (("gnu" . "https://elpa.gnu.org/packages/")
     ("melpa-stable" . "https://stable.melpa.org/packages/")
     ("melpa" . "http://melpa.org/packages/"))))
 '(package-selected-packages
   (quote
    (groovy-mode clang-format vlf company-ycmd flycheck-ycmd ycmd modern-cpp-font-lock swiper ivy exec-path-from-shell markdown-mode)))
 '(python-indent-guess-indent-offset nil)
 '(revert-without-query nil)
 '(safe-local-variable-values (quote ((backup-inhibited . t))))
 '(save-place t nil (saveplace))
 '(savehist-file "~/.emacs.history")
 '(savehist-mode t nil (savehist))
 '(select-enable-clipboard t)
 '(select-enable-primary t)
 '(shell-prompt-pattern "^[^#$%>
]*[#$%>] *")
 '(show-paren-mode t)
 '(show-trailing-whitespace t)
 '(split-width-threshold nil)
 '(ssh-directory-tracking-mode t)
 '(swiper-include-line-number-in-search t)
 '(tool-bar-mode nil)
 '(tramp-debug-buffer t)
 '(tramp-terminal-type "tramp" nil (tramp))
 '(truncate-partial-width-windows nil)
 '(uniquify-buffer-name-style (quote post-forward-angle-brackets) nil (uniquify))
 '(vc-diff-switches "-u")
 '(visible-bell nil)
 '(warning-suppress-types (quote ((undo discard-info))))
 '(windmove-wrap-around t)
 '(ycmd-global-config "/Users/jimix/.ycm_extra_conf.py")
 '(ycmd-server-command
   (quote
    ("python" "/Users/jimix/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd"))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "black" :foreground "yellow" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 150 :width normal :foundry "nil" :family "Inconsolata"))))
 '(cursor ((t (:background "OrangeRed"))))
 '(ebrowse-member-class ((t (:background "gold" :foreground "purple"))))
 '(ebrowse-root-class ((t (:background "gold" :foreground "blue1" :weight bold))))
 '(region ((((class color) (min-colors 88) (background dark)) (:background "grey40"))))
 '(ruler-mode-pad ((t (:inherit ruler-mode-default :background "grey64" :foreground "white"))))
 '(trailing-whitespace ((t (:background "magenta"))))
 '(vc-annotate-face-3F3FFF ((t (:foreground "light coral"))) t)
 '(which-func ((((class color) (min-colors 88) (background dark)) (:background "black" :foreground "yellow")))))
